import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Sidbar from "../components/sidbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-400 bg-[#1d2125]`}
      >
        <div className="flex h-[100dvh] flex-col-reverse md:flex-row">
          <div className="bg-[#161a1d] rounded-lg m-2 p-3 md:w-[180px]">
            <Sidbar />
          </div>
          <div className="flex-1 bg-[#161a1d] rounded-lg m-2 p-3 mb-0 md:ml-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
